apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: kp
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: kp
    spec:
      containers:
        - name: kp
          image: kapasrijkubacr.azurecr.io/kp
          ports:
          - containerPort: 8080